from __future__ import annotations

import csv
import re
import unittest
from html.parser import HTMLParser
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
APPENDIX_SOURCE = PROJECT_ROOT / "reports" / "policy-selection-technical-appendix.qmd"
APPENDIX_HTML = PROJECT_ROOT / "reports" / "policy-selection-technical-appendix.html"
SUMMARY_PATH = PROJECT_ROOT / "data" / "marts" / "policy_decision_summary.csv"
UNCERTAINTY_PATH = PROJECT_ROOT / "data" / "marts" / "policy_uncertainty_summary.csv"


class VisibleTextParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ignored_depth = 0
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in {"script", "style"}:
            self.ignored_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag in {"script", "style"}:
            self.ignored_depth -= 1

    def handle_data(self, data: str) -> None:
        if self.ignored_depth == 0:
            self.parts.append(data)

    @property
    def text(self) -> str:
        return " ".join(" ".join(self.parts).split())


class PolicyAppendixTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.source = APPENDIX_SOURCE.read_text(encoding="utf-8")

    def test_appendix_uses_versioned_analytical_sources(self) -> None:
        for path in (
            "../config/policy_scenarios.v1.json",
            "../data/marts/policy_case_comparison.csv",
            "../data/marts/policy_decision_summary.csv",
            "../data/marts/policy_uncertainty_summary.csv",
        ):
            self.assertIn(path, self.source)
        self.assertIn("selected_for_shadow_evaluation", self.source)
        self.assertIn("internal_cost_p50", self.source)

    def test_appendix_has_captioned_visual_and_table_contract(self) -> None:
        self.assertEqual(self.source.count("#| fig-cap:"), 1)
        self.assertEqual(self.source.count("#| fig-alt:"), 1)
        self.assertIn('class="selection-flow"', self.source)
        self.assertIn("<figcaption><strong>How the candidate is selected.", self.source)
        self.assertEqual(self.source.count("#| tbl-cap:"), 4)
        for label in (
            "fig-qualified-cost",
            "tbl-candidate-policies",
            "tbl-guardrails",
            "tbl-uncertainty-methods",
            "tbl-decision-trace",
        ):
            self.assertIn(label, self.source)

    def test_appendix_explains_selection_without_overclaiming(self) -> None:
        required = (
            "policy selection**, not final predictive-model selection",
            "matched case-policy evaluations",
            "Metrics and hard guardrails",
            "Two uncertainty questions",
            "Synthetic post-stay scores are excluded",
            "stress-median cost",
            "What real data must establish",
            "does not establish actual policy effectiveness, savings, margins, or guest outcomes",
        )
        for text in required:
            self.assertIn(text, self.source)
        self.assertNotIn("projected savings", self.source.lower())

    def test_appendix_has_three_artifact_navigation_without_application_ui(self) -> None:
        self.assertIn("[Return to the executive brief](../index.html)", self.source)
        self.assertIn("[Download the executive PDF](hotel-comp-decision-framework.pdf)", self.source)
        self.assertIn("[Open the synthetic Decision Desk]", self.source)
        self.assertNotIn("tabset", self.source.lower())
        self.assertNotIn("dashboard", self.source.lower())

    def test_rendered_appendix_matches_generated_selection_when_available(self) -> None:
        if not APPENDIX_HTML.exists():
            self.skipTest("rendered appendix is generated by make technical-appendix")

        html = APPENDIX_HTML.read_text(encoding="utf-8")
        parser = VisibleTextParser()
        parser.feed(html)
        visible_text = parser.text

        with SUMMARY_PATH.open(encoding="utf-8", newline="") as handle:
            summary_rows = list(csv.DictReader(handle))
        with UNCERTAINTY_PATH.open(encoding="utf-8", newline="") as handle:
            uncertainty_rows = list(csv.DictReader(handle))

        selected = next(row for row in summary_rows if row["selected_for_shadow_evaluation"] == "true")
        uncertainty = next(row for row in uncertainty_rows if row["policy_id"] == selected["policy_id"])

        self.assertIn(selected["policy_label"], visible_text)
        self.assertIn(f"${float(selected['internal_cost_mid']):,.0f}", visible_text)
        self.assertIn(f"${float(uncertainty['internal_cost_p50']):,.0f}", visible_text)
        self.assertIn(f"${float(uncertainty['internal_cost_p05']):,.0f}", visible_text)
        self.assertIn(f"${float(uncertainty['internal_cost_p95']):,.0f}", visible_text)
        self.assertEqual(len(re.findall(r"<table\b", html)), 4)
        self.assertEqual(len(re.findall(r"<img\b[^>]*role=\"img\"", html)), 1)
        self.assertIn('class="selection-flow', html)
        self.assertNotIn("<button", html)


if __name__ == "__main__":
    unittest.main()
