USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS HOTEL_COMP_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Small development warehouse for the hotel comp policy prototype.';

CREATE DATABASE IF NOT EXISTS HOTEL_COMP_POLICY_MODEL
  COMMENT = 'Optional Snowflake warehouse for the hotel comp policy prototype.';

CREATE SCHEMA IF NOT EXISTS HOTEL_COMP_POLICY_MODEL.RAW;
CREATE SCHEMA IF NOT EXISTS HOTEL_COMP_POLICY_MODEL.STAGING;
CREATE SCHEMA IF NOT EXISTS HOTEL_COMP_POLICY_MODEL.MARTS;
CREATE SCHEMA IF NOT EXISTS HOTEL_COMP_POLICY_MODEL.AUDIT;

CREATE ROLE IF NOT EXISTS HOTEL_COMP_DEV_ROLE
  COMMENT = 'Project-scoped role for loading and querying the hotel comp policy prototype.';

GRANT USAGE ON WAREHOUSE HOTEL_COMP_WH TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT USAGE ON DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT CREATE SCHEMA ON DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA HOTEL_COMP_POLICY_MODEL.RAW TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA HOTEL_COMP_POLICY_MODEL.STAGING TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA HOTEL_COMP_POLICY_MODEL.MARTS TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA HOTEL_COMP_POLICY_MODEL.AUDIT TO ROLE HOTEL_COMP_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES
  IN DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS
  IN DATABASE HOTEL_COMP_POLICY_MODEL TO ROLE HOTEL_COMP_DEV_ROLE;

-- Set SNOWFLAKE_BOOTSTRAP_USER when running the bootstrap command to grant
-- HOTEL_COMP_DEV_ROLE to a project user without hard-coding an account identity.
