USE ROLE HOTEL_COMP_DEV_ROLE;
USE WAREHOUSE HOTEL_COMP_WH;
USE DATABASE HOTEL_COMP_POLICY_MODEL;

CREATE OR REPLACE VIEW MARTS.VW_COMP_DECISION_SUMMARY AS
SELECT
  COUNT(*) AS RECOVERY_CASES,
  SUM(TRY_TO_DOUBLE(RECOMMENDED_COMP_VALUE)) AS RECOMMENDED_GUEST_VALUE,
  SUM(TRY_TO_DOUBLE(ESTIMATED_INTERNAL_COST)) AS ESTIMATED_INTERNAL_COST,
  SUM(TRY_TO_DOUBLE(INTERNAL_COST_LOW)) AS INTERNAL_COST_LOW,
  SUM(TRY_TO_DOUBLE(INTERNAL_COST_HIGH)) AS INTERNAL_COST_HIGH,
  SUM(TRY_TO_DOUBLE(EXPECTED_RECOVERY_VALUE)) AS EXPECTED_RECOVERY_VALUE,
  MEDIAN(TRY_TO_DOUBLE(RECOMMENDATION_STABILITY)) AS MEDIAN_RECOMMENDATION_STABILITY,
  SUM(IFF(LOWER(DECISION_CONFIDENCE) = 'low', 1, 0)) AS LOW_CONFIDENCE_CASES,
  SUM(IFF(LOWER(MANAGER_REVIEW_FLAG) = 'true', 1, 0)) AS MANAGER_REVIEW_CASES,
  SUM(IFF(TRY_TO_DOUBLE(REVIEW_RISK_SCORE) >= 0.70, 1, 0)) AS HIGH_REVIEW_RISK_CASES
FROM MARTS.MART_COMP_RECOMMENDATIONS;

CREATE OR REPLACE VIEW MARTS.VW_COMP_MIX AS
SELECT
  COMP_LABEL,
  COUNT(*) AS CASES,
  SUM(TRY_TO_DOUBLE(RECOMMENDED_COMP_VALUE)) AS RECOMMENDED_GUEST_VALUE,
  SUM(TRY_TO_DOUBLE(ESTIMATED_INTERNAL_COST)) AS ESTIMATED_INTERNAL_COST
FROM MARTS.MART_COMP_RECOMMENDATIONS
GROUP BY COMP_LABEL
ORDER BY RECOMMENDED_GUEST_VALUE DESC;

CREATE OR REPLACE VIEW MARTS.VW_MANAGER_REVIEW_QUEUE AS
SELECT
  RECOVERY_CASE_ID,
  SERVICE_TICKET_ID,
  GUEST_TIER,
  TRAVELER_SEGMENT,
  FAILURE_CATEGORY,
  SEVERITY,
  RECOVERY_NEED_SCORE,
  REVIEW_RISK_SCORE,
  RECOMMENDED_COMP_VALUE,
  INTERNAL_COST_LOW,
  INTERNAL_COST_HIGH,
  COMP_LABEL,
  MANAGER_REVIEW_FLAG,
  DECISION_CONFIDENCE,
  RECOMMENDATION_STABILITY,
  POLICY_VERSION,
  RECOMMENDATION_COUNTERFACTUALS,
  RESERVATION_MATCH_CONFIDENCE,
  DATA_QUALITY_FLAGS
FROM MARTS.MART_COMP_RECOMMENDATIONS
WHERE LOWER(MANAGER_REVIEW_FLAG) = 'true'
   OR LOWER(DECISION_CONFIDENCE) <> 'high'
   OR TRY_TO_DOUBLE(RESERVATION_MATCH_CONFIDENCE) < 0.75
ORDER BY TRY_TO_DOUBLE(RECOVERY_NEED_SCORE) DESC, TRY_TO_DOUBLE(ESTIMATED_LIFETIME_VALUE) DESC;

CREATE OR REPLACE VIEW AUDIT.VW_AUDIT_DECISION_SIGNAL AS
SELECT
  AUDIT_CLASS,
  COUNT(*) AS CASES,
  SUM(TRY_TO_DOUBLE(RECOMMENDED_COMP_VALUE)) AS RECOMMENDED_GUEST_VALUE,
  SUM(TRY_TO_DOUBLE(RECOMMENDED_INTERNAL_COST)) AS RECOMMENDED_INTERNAL_COST,
  SUM(TRY_TO_DOUBLE(RECOMMENDED_MINUS_ACTUAL_VALUE)) AS RECOMMENDED_MINUS_ACTUAL_VALUE
FROM MARTS.MART_COMP_POLICY_AUDIT
GROUP BY AUDIT_CLASS
ORDER BY CASES DESC;

CREATE OR REPLACE VIEW AUDIT.VW_SOURCE_QUALITY_SNAPSHOT AS
SELECT 'tickets_missing_reservation_id' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_SERVICE_TICKETS
WHERE PMS_RESERVATION_ID IS NULL OR PMS_RESERVATION_ID = ''
UNION ALL
SELECT 'tickets_missing_severity' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_SERVICE_TICKETS
WHERE SEVERITY_RAW IS NULL OR SEVERITY_RAW = ''
UNION ALL
SELECT 'crm_duplicate_profiles' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_GUEST_PROFILES_CRM
WHERE LOWER(DUPLICATE_PROFILE_FLAG) = 'true'
UNION ALL
SELECT 'comp_ledger_orphan_records' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_COMP_LEDGER
WHERE SERVICE_TICKET_ID IS NULL OR SERVICE_TICKET_ID = ''
UNION ALL
SELECT 'low_confidence_recovery_cases' AS METRIC, COUNT(*) AS ROW_COUNT
FROM MARTS.MART_RECOVERY_CASES
WHERE TRY_TO_DOUBLE(RESERVATION_MATCH_CONFIDENCE) > 0
  AND TRY_TO_DOUBLE(RESERVATION_MATCH_CONFIDENCE) < 0.75;

CREATE OR REPLACE VIEW MARTS.VW_PUBLIC_PRICING_CONTEXT AS
SELECT
  CONTEXT_DATE,
  TARGET_PUBLIC_RATE,
  COMP_SET_MEDIAN_RATE,
  PUBLIC_RATE_PRESSURE_INDEX,
  HIGH_DEMAND_RATE_FLAG,
  UPGRADE_OPPORTUNITY_COST_PROXY,
  REFUND_COST_PRESSURE,
  RATE_CONTEXT_CONFIDENCE,
  PRICING_PROVENANCE
FROM MARTS.MART_PUBLIC_PRICING_CONTEXT
ORDER BY TRY_TO_DOUBLE(PUBLIC_RATE_PRESSURE_INDEX) DESC;

CREATE OR REPLACE VIEW AUDIT.VW_EXTERNAL_CONTEXT_SOURCES AS
SELECT 'rate_shop_snapshots' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_RATE_SHOP_SNAPSHOTS
UNION ALL
SELECT 'property_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_PROPERTY_CONTEXT
UNION ALL
SELECT 'proper_public_value_anchors' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_PROPER_PUBLIC_VALUE_ANCHORS
UNION ALL
SELECT 'review_risk_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_REVIEW_RISK_CONTEXT
UNION ALL
SELECT 'local_demand_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_LOCAL_DEMAND_CONTEXT;

CREATE OR REPLACE VIEW MARTS.VW_EXTERNAL_CONTEXT_MODEL_IMPACT AS
SELECT
  COMPARISON_ID,
  DECISION_SIGNAL,
  CONTROL_COMP_CODE,
  CONTEXT_COMP_CODE,
  RECOMMENDATION_CHANGED,
  RECOMMENDED_VALUE_DELTA,
  INTERNAL_COST_DELTA,
  CONTEXT_REASON_CODES
FROM MARTS.MART_EXTERNAL_CONTEXT_MODEL_IMPACT
ORDER BY DECISION_SIGNAL;
