USE ROLE HOTEL_COMP_DEV_ROLE;
USE WAREHOUSE HOTEL_COMP_WH;
USE DATABASE HOTEL_COMP_POLICY_MODEL;

CREATE OR REPLACE VIEW MARTS.VW_COMP_DECISION_SUMMARY AS
SELECT
  COUNT(*) AS RECOVERY_CASES,
  SUM(RECOMMENDED_COMP_VALUE) AS RECOMMENDED_GUEST_VALUE,
  SUM(ESTIMATED_INTERNAL_COST) AS ESTIMATED_INTERNAL_COST,
  SUM(INTERNAL_COST_LOW) AS INTERNAL_COST_LOW,
  SUM(INTERNAL_COST_HIGH) AS INTERNAL_COST_HIGH,
  MEDIAN(RECOMMENDATION_STABILITY) AS MEDIAN_RECOMMENDATION_STABILITY,
  SUM(IFF(LOWER(DECISION_CONFIDENCE) = 'low', 1, 0)) AS LOW_CONFIDENCE_CASES,
  SUM(IFF(MANAGER_REVIEW_FLAG, 1, 0)) AS MANAGER_REVIEW_CASES,
  SUM(IFF(REVIEW_RISK_SCORE >= 0.70, 1, 0)) AS HIGH_REVIEW_RISK_CASES
FROM MARTS.MART_COMP_RECOMMENDATIONS;

CREATE OR REPLACE VIEW MARTS.VW_COMP_MIX AS
SELECT
  COMP_LABEL,
  COUNT(*) AS CASES,
  SUM(RECOMMENDED_COMP_VALUE) AS RECOMMENDED_GUEST_VALUE,
  SUM(ESTIMATED_INTERNAL_COST) AS ESTIMATED_INTERNAL_COST
FROM MARTS.MART_COMP_RECOMMENDATIONS
GROUP BY COMP_LABEL
ORDER BY RECOMMENDED_GUEST_VALUE DESC;

CREATE OR REPLACE VIEW MARTS.VW_MANAGER_REVIEW_QUEUE AS
SELECT
  RECOVERY_CASE_ID,
  SERVICE_TICKET_ID,
  GUEST_TIER,
  TRAVELER_SEGMENT,
  FAILURE_CATEGORY,
  SEVERITY,
  RECOVERY_NEED_SCORE,
  REVIEW_RISK_SCORE,
  RECOMMENDED_COMP_VALUE,
  INTERNAL_COST_LOW,
  INTERNAL_COST_HIGH,
  COMP_LABEL,
  MANAGER_REVIEW_FLAG,
  DECISION_CONFIDENCE,
  RECOMMENDATION_STABILITY,
  POLICY_VERSION,
  RECOMMENDATION_COUNTERFACTUALS,
  RESERVATION_MATCH_CONFIDENCE,
  DATA_QUALITY_FLAGS
FROM MARTS.MART_COMP_RECOMMENDATIONS
WHERE MANAGER_REVIEW_FLAG
   OR LOWER(DECISION_CONFIDENCE) <> 'high'
   OR RESERVATION_MATCH_CONFIDENCE < 0.75
ORDER BY RECOVERY_NEED_SCORE DESC, ESTIMATED_LIFETIME_VALUE DESC;

CREATE OR REPLACE VIEW AUDIT.VW_AUDIT_DECISION_SIGNAL AS
SELECT
  AUDIT_CLASS,
  COUNT(*) AS CASES,
  SUM(RECOMMENDED_COMP_VALUE) AS RECOMMENDED_GUEST_VALUE,
  SUM(RECOMMENDED_INTERNAL_COST) AS RECOMMENDED_INTERNAL_COST,
  SUM(RECOMMENDED_MINUS_ACTUAL_VALUE) AS RECOMMENDED_MINUS_ACTUAL_VALUE
FROM MARTS.MART_COMP_POLICY_AUDIT
GROUP BY AUDIT_CLASS
ORDER BY CASES DESC;

CREATE OR REPLACE VIEW AUDIT.VW_SOURCE_QUALITY_SNAPSHOT AS
SELECT 'tickets_missing_reservation_id' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_SERVICE_TICKETS
WHERE PMS_RESERVATION_ID IS NULL OR PMS_RESERVATION_ID = ''
UNION ALL
SELECT 'tickets_missing_severity' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_SERVICE_TICKETS
WHERE SEVERITY_RAW IS NULL OR SEVERITY_RAW = ''
UNION ALL
SELECT 'crm_duplicate_profiles' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_GUEST_PROFILES_CRM
WHERE LOWER(DUPLICATE_PROFILE_FLAG) = 'true'
UNION ALL
SELECT 'comp_ledger_orphan_records' AS METRIC, COUNT(*) AS ROW_COUNT
FROM RAW.STG_COMP_LEDGER
WHERE SERVICE_TICKET_ID IS NULL OR SERVICE_TICKET_ID = ''
UNION ALL
SELECT 'low_confidence_recovery_cases' AS METRIC, COUNT(*) AS ROW_COUNT
FROM MARTS.MART_RECOVERY_CASES
WHERE RESERVATION_MATCH_CONFIDENCE > 0
  AND RESERVATION_MATCH_CONFIDENCE < 0.75;

CREATE OR REPLACE VIEW MARTS.VW_PUBLIC_PRICING_CONTEXT AS
SELECT
  CONTEXT_DATE,
  TARGET_PUBLIC_RATE,
  COMP_SET_MEDIAN_RATE,
  PUBLIC_RATE_PRESSURE_INDEX,
  HIGH_DEMAND_RATE_FLAG,
  UPGRADE_OPPORTUNITY_COST_PROXY,
  REFUND_COST_PRESSURE,
  RATE_CONTEXT_CONFIDENCE,
  PRICING_PROVENANCE
FROM MARTS.MART_PUBLIC_PRICING_CONTEXT
ORDER BY PUBLIC_RATE_PRESSURE_INDEX DESC;

CREATE OR REPLACE VIEW AUDIT.VW_EXTERNAL_CONTEXT_SOURCES AS
SELECT 'rate_shop_snapshots' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_RATE_SHOP_SNAPSHOTS
UNION ALL
SELECT 'property_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_PROPERTY_CONTEXT
UNION ALL
SELECT 'proper_public_value_anchors' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_PROPER_PUBLIC_VALUE_ANCHORS
UNION ALL
SELECT 'review_risk_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_REVIEW_RISK_CONTEXT
UNION ALL
SELECT 'local_demand_context' AS SOURCE_LAYER, COUNT(*) AS ROW_COUNT FROM RAW.STG_LOCAL_DEMAND_CONTEXT;

CREATE OR REPLACE VIEW MARTS.VW_EXTERNAL_CONTEXT_MODEL_IMPACT AS
SELECT
  COMPARISON_ID,
  DECISION_SIGNAL,
  CONTROL_COMP_CODE,
  CONTEXT_COMP_CODE,
  RECOMMENDATION_CHANGED,
  RECOMMENDED_VALUE_DELTA,
  INTERNAL_COST_DELTA,
  CONTEXT_REASON_CODES
FROM MARTS.MART_EXTERNAL_CONTEXT_MODEL_IMPACT
ORDER BY DECISION_SIGNAL;

CREATE OR REPLACE VIEW MARTS.VW_POLICY_DECISION_RECOMMENDATION AS
SELECT
  POLICY_ID,
  POLICY_LABEL,
  ADEQUACY_RATE AS SAFE_RECOVERY_PATH_RATE,
  GESTURE_ADEQUACY_RATE,
  HIGH_RISK_UNDER_RECOVERY_RATE,
  INTERNAL_COST_MID,
  DIRECT_ROOM_REFUND_VALUE,
  MANAGER_REVIEW_RATE,
  JOINT_GUARDRAIL_PASS_PROBABILITY,
  POLICY_SELECTION_PROBABILITY,
  EXECUTIVE_RECOMMENDATION,
  EVIDENCE_BOUNDARY
FROM MARTS.MART_POLICY_DECISION_SUMMARY
WHERE SELECTED_FOR_PILOT;

CREATE OR REPLACE VIEW MARTS.VW_POLICY_TRADEOFF AS
SELECT
  *
FROM MARTS.MART_POLICY_DECISION_SUMMARY
ORDER BY IFF(SELECTED_FOR_PILOT, 1, 0) DESC,
         INTERNAL_COST_MID;

CREATE OR REPLACE VIEW MARTS.VW_POLICY_SEGMENT_DIAGNOSTICS AS
SELECT *
FROM MARTS.MART_POLICY_SEGMENT_DIAGNOSTICS
WHERE NOT SUPPRESSED_SMALL_GROUP;

CREATE OR REPLACE VIEW MARTS.VW_POLICY_UNCERTAINTY AS
SELECT
  POLICY_ID,
  POLICY_LABEL,
  SENSITIVITY_DRAWS,
  JOINT_GUARDRAIL_PASS_PROBABILITY,
  ADEQUACY_GUARDRAIL_PASS_PROBABILITY,
  HIGH_RISK_GUARDRAIL_PASS_PROBABILITY,
  OPERATIONAL_GUARDRAIL_PASS_PROBABILITY,
  DATA_HOLD_GUARDRAIL_PASS_PROBABILITY,
  TIER_FIVE_REVIEW_GUARDRAIL_PASS_PROBABILITY,
  INTERNAL_COST_P05,
  INTERNAL_COST_P50,
  INTERNAL_COST_P95,
  POLICY_SELECTION_PROBABILITY,
  UNCERTAINTY_PROVENANCE
FROM MARTS.MART_POLICY_UNCERTAINTY_SUMMARY
ORDER BY POLICY_SELECTION_PROBABILITY DESC;
