USE ROLE HOTEL_COMP_DEV_ROLE;
USE WAREHOUSE HOTEL_COMP_WH;
USE DATABASE HOTEL_COMP_POLICY_MODEL;

SELECT * FROM MARTS.VW_COMP_DECISION_SUMMARY;
SELECT * FROM MARTS.VW_COMP_MIX ORDER BY RECOMMENDED_GUEST_VALUE DESC;
SELECT * FROM MARTS.VW_MANAGER_REVIEW_QUEUE LIMIT 20;
SELECT * FROM AUDIT.VW_AUDIT_DECISION_SIGNAL;
SELECT * FROM AUDIT.VW_SOURCE_QUALITY_SNAPSHOT;
SELECT * FROM MARTS.VW_PUBLIC_PRICING_CONTEXT LIMIT 20;
SELECT * FROM AUDIT.VW_EXTERNAL_CONTEXT_SOURCES;
SELECT * FROM MARTS.VW_EXTERNAL_CONTEXT_MODEL_IMPACT;
